import { NextRequest, NextResponse } from 'next/server';
import { createClient } from '@supabase/supabase-js';

// ✅ Uses the fork to prevent the DOMMatrix crash on Vercel!
const pdfParse = require('pdf-parse-fork');

const supabaseAdmin = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
);

function cleanTypingText(rawText: string): string {
  return rawText
    // 1. Remove page numbers or page separators
    .replace(/--- PAGE \d+ ---/gi, '')
    // 2. Remove standard grade headers (e.g., E JUNIOR 22, E SENIOR 14)
    .replace(/E\s+(JUNIOR|SENIOR)\s+\d+/gi, '')
    // 3. Remove the standard Title
    .replace(/Typing Practice Test/gi, '')
    // 4. Remove website footers
    .replace(/Generated by\s+successtyping\.com/gi, '')
    .replace(/Practice makes perfect!/gi, '')
    // 5. Clean up any leftover floating dots/bullets
    .replace(/•/g, '')
    // 6. Collapse multiple spaces and line breaks into single spaces
    .replace(/\s+/g, ' ')
    .trim();
}

export async function POST(req: NextRequest) {
  try {
    const formData = await req.formData();
    const files = formData.getAll('files') as File[];
    const language = formData.get('language') as string;
    const level = formData.get('level') as string;

    if (!files || files.length === 0) {
      return NextResponse.json({ error: 'No files uploaded' }, { status: 400 });
    }

    const uploadResults = [];

    for (const file of files) {
      try {
        const arrayBuffer = await file.arrayBuffer();
        const buffer = Buffer.from(arrayBuffer);
        
        const pdfData = await pdfParse(buffer);
        
        // 🚀 We clean the text before sending it to Supabase!
        const cleanedText = cleanTypingText(pdfData.text);

        if (cleanedText && cleanedText.length > 10) {
          const { error } = await supabaseAdmin
            .from('passages')
            .insert([
              {
                text: cleanedText,
                language: language,
                level: level,
              }
            ]);

          if (error) throw error;
          uploadResults.push({ fileName: file.name, status: 'Success ✅' });
        } else {
          uploadResults.push({ fileName: file.name, status: 'Failed: No readable text ❌' });
        }
      } catch (err: any) {
        console.error(`Error with file ${file.name}:`, err);
        uploadResults.push({ fileName: file.name, status: 'Failed: Parsing error ❌' });
      }
    }

    return NextResponse.json({ success: true, results: uploadResults });
  } catch (error: any) {
    console.error('Bulk Upload Error:', error);
    return NextResponse.json({ error: 'Failed to process bulk upload' }, { status: 500 });
  }
}